post_install() {
	cat <<EOM

:: To be able to build Alpine packages in a clean chroot with "abuild rootbld",
   you need to generate a public / private rsa key pair with the "abuild-keygen" tool,
   and add your user to the "abuild" group (requires a logout / login to take effect):

   $ abuild-keygen -a -i
   # usermod -aG abuild "username"

   See https://wiki.archlinux.org/title/Abuild for more details.

EOM
}
